spring.application.name=ParkplayFinal

spring.datasource.url=jdbc:mysql://localhost:3306/parkplay_db?allowPublicKeyRetrieval=true&useSSL=false

spring.datasource.username=root

spring.datasource.password=parolaProiectDBP3

spring.sql.init.mode=always

logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG